# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):

        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 320)
        Dialog.setMinimumSize(QtCore.QSize(320, 320))
        Dialog.setMaximumSize(QtCore.QSize(320, 320))
        self.push_button_ok = QtWidgets.QPushButton(Dialog)
        self.push_button_ok.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.push_button_ok.setObjectName("push_button_ok")
        self.push_button_cancel = QtWidgets.QPushButton(Dialog)
        self.push_button_cancel.setGeometry(QtCore.QRect(220, 280, 75, 23))
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.input_url = QtWidgets.QLineEdit(Dialog)
        self.input_url.setGeometry(QtCore.QRect(10, 60, 301, 20))
        self.input_url.setObjectName("input_url")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.button_only_audio = QtWidgets.QRadioButton(Dialog)
        self.button_only_audio.setGeometry(QtCore.QRect(10, 100, 141, 16))
        self.button_only_audio.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.button_only_audio.setObjectName("button_only_audio")
        self.button_video = QtWidgets.QRadioButton(Dialog)
        self.button_video.setGeometry(QtCore.QRect(160, 100, 151, 17))
        self.button_video.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.button_video.setObjectName("button_video")

        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Youtube Video Downloader", "Youtube Video Downloader"))
        self.push_button_ok.setText(_translate("Dialog", "OK"))
        self.push_button_cancel.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Youtube Video Downloader"))
        self.label_2.setText(_translate("Dialog", "URL:"))
        self.button_only_audio.setText(_translate("Dialog", "MP4 solo audio"))
        self.button_video.setText(_translate("Dialog", "MP4 audio y video"))
